# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: We Enhance IT
email: info@weenhanceit.com
description: > # this means to ignore newlines until "baseurl:"
  Enabling your people to be more effective through technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weenhanceit.github.io" # the base hostname & protocol for your site
twitter_username: weenhanceit
github_username:  weenhanceit
company_name: "We Enhance IT"

# Build settings
markdown: kramdown
